version: '3'

services:
  test_1:
    build:
        context: ./test_1
    networks:
        testing_net:
          ipv4_address: 172.29.1.1

  test_2:
    build:
      context: ./test_1
      args:
        machine_config: test_config
    networks:
        testing_net:
            ipv4_address: 172.29.1.2

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/16
