version: '3'

services:
  test_1:
    container_name: test_1
    build:
        context: ./test_1
    networks:
        testing_net:
          ipv4_address: 172.28.1.1

  test_2:
    container_name: test_2
    build:
      context: ./test_1
    networks:
        testing_net:
            ipv4_address: 172.28.1.2

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
