apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: myApp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myApp
  template:
    metadata:
      labels:
        app: myApp
    spec:
      containers:
      - name: test
        image: localhost:32000/testing:k8s
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
