version: '3'

services:
  emulator1:
    build:
        context: ./Redfish_Emulator_Docker
    networks:
        redfish_net: 
            ipv4_address: 172.29.1.1

  emulator2:
    build:
        context: ./Redfish_Emulator_Docker
        #        args:
        #            machine_config: cameron_config
    networks:
        redfish_net: 
            ipv4_address: 172.29.1.2

networks:
  redfish_net:
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/16
