version: '3'

services:
  emulator1:
    build:
        context: .
    networks:
        redfish_net: 
            ipv4_address: 172.29.1.1

  emulator2:
    build:
        context: .
        #        args:
        #            machine_config: master 
    networks:
        redfish_net: 
            ipv4_address: 172.29.1.2

networks:
  redfish_net:
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/16
